---

name: main-build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: build
        shell: bash
        run: |
          ./entrypoint branch_main
        env:
          SECRET_REGISTRY_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
