---

name: release
on:
  push:
    tags:
      - "v*"

jobs:
  build_push:
    name: "build_push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: release
        shell: bash
        run: |
          ./entrypoint build_push
        env:
          REGISTRY_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

  github_release:
    name: "github_release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: release
        shell: bash
        run: |
          ./entrypoint github_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
