---

name: release
on:
  push:
    tags:
      - "v*"

jobs:
  version_tag:
    name: "version_tag"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: release
        shell: bash
        run: |
          ./entrypoint version_tag
        env:
          SECRET_REGISTRY_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
